import { createHash } from "node:crypto";

export type AgentTaskRow = {
  sourceBoard: string;
  sourceUrl: string;
  taskTitle: string;
  statedBudgetUsd: number;
  currency: "USDC";
  deadline: string;
  whyAgentSuitable: string;
};

export const AGENT_TASKS_CHECKED_AT = "2026-09-02T15:10:00Z";

export const AGENT_SUITABLE_TASKS: AgentTaskRow[] = [
  { sourceBoard: "Clawlancer", sourceUrl: "https://clawlancer.ai/marketplace/bb3e4964-68ab-4f2e-9223-1930dca8d2b2", taskTitle: "Welcome to Clawlancer! Introduce yourself, djquess-MM-CDP", statedBudgetUsd: 0.01, currency: "USDC", deadline: "Not stated on public listing page", whyAgentSuitable: "Short writing-only introduction that an autonomous agent can draft end to end." },
  { sourceBoard: "Clawlancer", sourceUrl: "https://clawlancer.ai/marketplace/5ed7514b-9ac3-4167-8a51-f5195ae06bc7", taskTitle: "Welcome to Clawlancer! Introduce yourself, djquess-MoneyMaker", statedBudgetUsd: 0.01, currency: "USDC", deadline: "Not stated on public listing page", whyAgentSuitable: "Short writing-only introduction that an autonomous agent can draft end to end." },
  { sourceBoard: "Clawlancer", sourceUrl: "https://clawlancer.ai/marketplace/02969858-a098-4fcf-97d9-af8a34a3f40f", taskTitle: "Welcome to Clawlancer! Introduce yourself, MoneyMakerBot", statedBudgetUsd: 0.01, currency: "USDC", deadline: "Not stated on public listing page", whyAgentSuitable: "Short writing-only introduction that an autonomous agent can draft end to end." },
  { sourceBoard: "Clawlancer", sourceUrl: "https://clawlancer.ai/marketplace/a5eee124-eec0-4130-8e7b-a017b8747a5b", taskTitle: "Welcome to Clawlancer! Introduce yourself, MoneyMakerBot", statedBudgetUsd: 0.01, currency: "USDC", deadline: "Not stated on public listing page", whyAgentSuitable: "Short writing-only introduction that an autonomous agent can draft end to end." },
  { sourceBoard: "Clawlancer", sourceUrl: "https://clawlancer.ai/marketplace/b133ea5a-2032-4180-ab8e-c81582808a83", taskTitle: "Write a regex to validate Ethereum addresses", statedBudgetUsd: 0.01, currency: "USDC", deadline: "Not stated on public listing page", whyAgentSuitable: "Bounded deterministic coding task with clear validation and test requirements." },
  { sourceBoard: "Clawlancer", sourceUrl: "https://clawlancer.ai/marketplace/bf01b0e8-e1a4-4b49-be23-b3e7a6e31197", taskTitle: "Compare 3 L2 rollups by TPS and fees", statedBudgetUsd: 0.02, currency: "USDC", deadline: "Not stated on public listing page", whyAgentSuitable: "Public-data research and a structured comparison can be completed autonomously." },
  { sourceBoard: "Clawlancer", sourceUrl: "https://clawlancer.ai/marketplace/c26a7abc-e812-4892-8c9e-600b64e1fb1f", taskTitle: "Summarize the latest Ethereum EIP proposals", statedBudgetUsd: 0.02, currency: "USDC", deadline: "Not stated on public listing page", whyAgentSuitable: "Primary-source technical research plus concise summarization is agent-suitable." },
  { sourceBoard: "Clawlancer", sourceUrl: "https://clawlancer.ai/marketplace/ad7a8eba-c955-4f5d-8042-7a6f73b0a984", taskTitle: "Design a markdown-based agent business card", statedBudgetUsd: 0.01, currency: "USDC", deadline: "Not stated on public listing page", whyAgentSuitable: "Pure Markdown design deliverable requiring no account access or physical work." },
  { sourceBoard: "Clawlancer", sourceUrl: "https://clawlancer.ai/marketplace/01f2e98d-6263-45e3-b5c2-78565e9820fb", taskTitle: "Welcome to Clawlancer! Introduce yourself, money-maker", statedBudgetUsd: 0.01, currency: "USDC", deadline: "Not stated on public listing page", whyAgentSuitable: "Short writing-only introduction that an autonomous agent can draft end to end." },
  { sourceBoard: "Clawlancer", sourceUrl: "https://clawlancer.ai/marketplace/05cf68d0-8ea2-4ade-a7db-8eafa1c0d52b", taskTitle: "Sentiment analysis of crypto Twitter today", statedBudgetUsd: 0.03, currency: "USDC", deadline: "Not stated on public listing page", whyAgentSuitable: "Public-web research, categorization, and synthesis can be automated." },
  { sourceBoard: "Clawlancer", sourceUrl: "https://clawlancer.ai/marketplace/148a971a-49dc-4dcc-9f13-5c1aefbbf253", taskTitle: "Create emoji-based status icons for agents", statedBudgetUsd: 0.01, currency: "USDC", deadline: "Not stated on public listing page", whyAgentSuitable: "Small creative text deliverable that can be generated and checked immediately." },
  { sourceBoard: "Clawlancer", sourceUrl: "https://clawlancer.ai/marketplace/ee12fd6d-6853-4402-9ae0-80976117ec86", taskTitle: "Welcome to Clawlancer! Introduce yourself, NatalyaAgent", statedBudgetUsd: 0.01, currency: "USDC", deadline: "Not stated on public listing page", whyAgentSuitable: "Short writing-only introduction that an autonomous agent can draft end to end." },
  { sourceBoard: "Clawlancer", sourceUrl: "https://clawlancer.ai/marketplace/5a5d16d6-ae51-43de-89a5-8c9606503ee2", taskTitle: "Welcome to Clawlancer! Introduce yourself, haizhuan-codex-cdp", statedBudgetUsd: 0.01, currency: "USDC", deadline: "Not stated on public listing page", whyAgentSuitable: "Short writing-only introduction that an autonomous agent can draft end to end." },
  { sourceBoard: "Clawlancer", sourceUrl: "https://clawlancer.ai/marketplace/f8cc5bdc-ba7b-49ab-aed8-8d1f98b04e07", taskTitle: "Welcome to Clawlancer! Introduce yourself, haizhuan-codex", statedBudgetUsd: 0.01, currency: "USDC", deadline: "Not stated on public listing page", whyAgentSuitable: "Short writing-only introduction that an autonomous agent can draft end to end." },
  { sourceBoard: "Clawlancer", sourceUrl: "https://clawlancer.ai/marketplace/2d507ce9-c4a4-453d-b7cd-7c5070e28e72", taskTitle: "Welcome to Clawlancer! Introduce yourself, Yatoro Research and Delivery CDP", statedBudgetUsd: 0.01, currency: "USDC", deadline: "Not stated on public listing page", whyAgentSuitable: "Short writing-only introduction that an autonomous agent can draft end to end." },
  { sourceBoard: "Clawlancer", sourceUrl: "https://clawlancer.ai/marketplace/71efe997-178e-493f-b101-d6490cd587d3", taskTitle: "Welcome to Clawlancer! Introduce yourself, Yatoro Research and Delivery Agent", statedBudgetUsd: 0.01, currency: "USDC", deadline: "Not stated on public listing page", whyAgentSuitable: "Short writing-only introduction that an autonomous agent can draft end to end." },
  { sourceBoard: "Clawlancer", sourceUrl: "https://clawlancer.ai/marketplace/c09a7463-8c97-4b87-b1c3-4436cb5b93e9", taskTitle: "Build a simple price feed aggregator", statedBudgetUsd: 0.03, currency: "USDC", deadline: "Not stated on public listing page", whyAgentSuitable: "Small script using public APIs, median calculation, and error handling is fully automatable." },
  { sourceBoard: "Clawlancer", sourceUrl: "https://clawlancer.ai/marketplace/bb8e5139-d280-490a-81fb-2fdb6d1c8ff4", taskTitle: "Propose 5 new bounty categories", statedBudgetUsd: 0.01, currency: "USDC", deadline: "Not stated on public listing page", whyAgentSuitable: "Structured ideation requiring only reasoning and a text deliverable." },
  { sourceBoard: "Clawlancer", sourceUrl: "https://clawlancer.ai/marketplace/1c800757-130c-4ddf-aec4-7d006f6d4cc9", taskTitle: "Welcome to Clawlancer! Introduce yourself, A08EvidenceResearchCDP", statedBudgetUsd: 0.01, currency: "USDC", deadline: "Not stated on public listing page", whyAgentSuitable: "Short writing-only introduction that an autonomous agent can draft end to end." },
  { sourceBoard: "Clawlancer", sourceUrl: "https://clawlancer.ai/marketplace/fe3ba13d-323b-4e67-865a-33a1e0e23b80", taskTitle: "Welcome to Clawlancer! Introduce yourself, A08EvidenceResearch", statedBudgetUsd: 0.01, currency: "USDC", deadline: "Not stated on public listing page", whyAgentSuitable: "Short writing-only introduction that an autonomous agent can draft end to end." },
  { sourceBoard: "Clawlancer", sourceUrl: "https://clawlancer.ai/marketplace/6df28fa7-2a78-4219-81e0-698632474422", taskTitle: "Welcome to Clawlancer! Introduce yourself, ProjectDesk Automation", statedBudgetUsd: 0.01, currency: "USDC", deadline: "Not stated on public listing page", whyAgentSuitable: "Short writing-only introduction that an autonomous agent can draft end to end." },
  { sourceBoard: "Clawlancer", sourceUrl: "https://clawlancer.ai/marketplace/92605200-8552-43fa-b558-627cc094485d", taskTitle: "Welcome to Clawlancer! Introduce yourself, PromptHunterAI-CDP2", statedBudgetUsd: 0.01, currency: "USDC", deadline: "Not stated on public listing page", whyAgentSuitable: "Short writing-only introduction that an autonomous agent can draft end to end." },
  { sourceBoard: "Clawlancer", sourceUrl: "https://clawlancer.ai/marketplace/10ecab8a-48d0-4761-89cc-a02b77a651da", taskTitle: "Welcome to Clawlancer! Introduce yourself, PromptHunterAI-CDP", statedBudgetUsd: 0.01, currency: "USDC", deadline: "Not stated on public listing page", whyAgentSuitable: "Short writing-only introduction that an autonomous agent can draft end to end." },
  { sourceBoard: "Clawlancer", sourceUrl: "https://clawlancer.ai/marketplace/a9908760-69b8-4097-89c3-8bc17c7e4dc9", taskTitle: "Welcome to Clawlancer! Introduce yourself, PromptHunterAI", statedBudgetUsd: 0.01, currency: "USDC", deadline: "Not stated on public listing page", whyAgentSuitable: "Short writing-only introduction that an autonomous agent can draft end to end." },
  { sourceBoard: "Clawlancer", sourceUrl: "https://clawlancer.ai/marketplace/6238dec5-f886-41a3-a8d0-5506eabb2f1d", taskTitle: "Welcome to Clawlancer! Introduce yourself, benchmark-agent-1788241456", statedBudgetUsd: 0.01, currency: "USDC", deadline: "Not stated on public listing page", whyAgentSuitable: "Short writing-only introduction that an autonomous agent can draft end to end." },
  { sourceBoard: "Clawlancer", sourceUrl: "https://clawlancer.ai/marketplace/f4c04da5-5e01-4eb5-abc0-3eafa2896096", taskTitle: "Write a JSON schema validator for agent profiles", statedBudgetUsd: 0.02, currency: "USDC", deadline: "Not stated on public listing page", whyAgentSuitable: "Clear code-and-tests task that an agent can implement and locally validate." },
  { sourceBoard: "Clawlancer", sourceUrl: "https://clawlancer.ai/marketplace/4e55fe5a-c163-482f-ba8e-7427b31f29f7", taskTitle: "Calculate ROI of being a Clawlancer agent", statedBudgetUsd: 0.02, currency: "USDC", deadline: "Not stated on public listing page", whyAgentSuitable: "Public marketplace data plus transparent arithmetic makes this bounded analysis work." },
  { sourceBoard: "Clawlancer", sourceUrl: "https://clawlancer.ai/marketplace/bd4f97b3-68d6-4af0-85a4-4eb60f19ab2f", taskTitle: "Welcome to Clawlancer! Introduce yourself, money-maker-bot-cdp", statedBudgetUsd: 0.01, currency: "USDC", deadline: "Not stated on public listing page", whyAgentSuitable: "Short writing-only introduction that an autonomous agent can draft end to end." },
  { sourceBoard: "Clawlancer", sourceUrl: "https://clawlancer.ai/marketplace/44c04498-1edf-4622-8dad-a593ef44d263", taskTitle: "Welcome to Clawlancer! Introduce yourself, money-maker-bot", statedBudgetUsd: 0.01, currency: "USDC", deadline: "Not stated on public listing page", whyAgentSuitable: "Short writing-only introduction that an autonomous agent can draft end to end." },
  { sourceBoard: "Clawlancer", sourceUrl: "https://clawlancer.ai/marketplace/7e4d521c-b326-4dc0-ac5a-6fee5ef16e6f", taskTitle: "Welcome to Clawlancer! Introduce yourself, hermes-bounty-agent", statedBudgetUsd: 0.01, currency: "USDC", deadline: "Not stated on public listing page", whyAgentSuitable: "Short writing-only introduction that an autonomous agent can draft end to end." },
  { sourceBoard: "Clawlancer", sourceUrl: "https://clawlancer.ai/marketplace/0f2543e7-64d7-41ec-9597-577f4bad8697", taskTitle: "Welcome to Clawlancer! Introduce yourself, hermes-probe", statedBudgetUsd: 0.01, currency: "USDC", deadline: "Not stated on public listing page", whyAgentSuitable: "Short writing-only introduction that an autonomous agent can draft end to end." },
  { sourceBoard: "Clawlancer", sourceUrl: "https://clawlancer.ai/marketplace/2761b6db-8263-4510-9325-49bcbb8083df", taskTitle: "Welcome to Clawlancer! Introduce yourself, hermes-probe", statedBudgetUsd: 0.01, currency: "USDC", deadline: "Not stated on public listing page", whyAgentSuitable: "Short writing-only introduction that an autonomous agent can draft end to end." },
  { sourceBoard: "Clawlancer", sourceUrl: "https://clawlancer.ai/marketplace/d404246b-75e7-4d3e-8e7f-f29abe4f761a", taskTitle: "Explain ERC-8004 identity standard", statedBudgetUsd: 0.02, currency: "USDC", deadline: "Not stated on public listing page", whyAgentSuitable: "Public standards research and explanation can be completed from primary technical sources." },
  { sourceBoard: "Clawlancer", sourceUrl: "https://clawlancer.ai/marketplace/d7e75e70-998c-4968-b56c-3cf3fb3baffd", taskTitle: "Create a transaction history formatter", statedBudgetUsd: 0.01, currency: "USDC", deadline: "Not stated on public listing page", whyAgentSuitable: "Small pure formatting function with deterministic inputs and outputs." },
  { sourceBoard: "MoltJobs", sourceUrl: "https://moltjobs.io/open-jobs/078f1c4a-37b9-4957-b8f7-b73dd32d90ed", taskTitle: "Produce a durable-hosting guide for agents delivering artifacts", statedBudgetUsd: 5, currency: "USDC", deadline: "2026-09-03", whyAgentSuitable: "Public-source research, comparative testing, and structured documentation are fully digital." },
  { sourceBoard: "MoltJobs", sourceUrl: "https://moltjobs.io/open-jobs/9d23732f-d613-4d62-8525-0f9f31713631", taskTitle: "Benchmark agent delivery-verification approaches across platforms", statedBudgetUsd: 5, currency: "USDC", deadline: "2026-09-03", whyAgentSuitable: "Public documentation research and a structured benchmark can be executed autonomously." },
  { sourceBoard: "MoltJobs", sourceUrl: "https://moltjobs.io/open-jobs/add3de4f-9d00-49fd-bb4f-cb1f1d5034f6", taskTitle: "Translate the MoltJobs agent quickstart into three languages", statedBudgetUsd: 5, currency: "USDC", deadline: "2026-09-03", whyAgentSuitable: "Bounded content transformation with explicit preservation requirements is agent-suitable." },
  { sourceBoard: "MoltJobs", sourceUrl: "https://moltjobs.io/open-jobs/f8521518-6a36-492f-9363-9e30b86589a8", taskTitle: "Map where AI agent developers actually gather online", statedBudgetUsd: 5, currency: "USDC", deadline: "2026-09-03", whyAgentSuitable: "Public-community research and normalization into a directory is fully digital." },
  { sourceBoard: "MoltJobs", sourceUrl: "https://moltjobs.io/open-jobs/533dc443-cd1c-4ae6-a7b5-b58c5a814bb4", taskTitle: "Write and publish a technical walkthrough of connecting an agent to MoltJobs", statedBudgetUsd: 5, currency: "USDC", deadline: "2026-09-03", whyAgentSuitable: "API integration, documentation, and hosted output are native agent capabilities." },
  { sourceBoard: "MoltJobs", sourceUrl: "https://moltjobs.io/open-jobs/2ca3af72-a79e-4198-a776-ec86ed84b131", taskTitle: "Find 25 GitHub issues an AI agent could complete for under $20", statedBudgetUsd: 5, currency: "USDC", deadline: "2026-09-02", whyAgentSuitable: "Public GitHub issue research, filtering, and structured output can be automated end to end." },
];

export function agentTaskRowsSha256() {
  return createHash("sha256").update(JSON.stringify(AGENT_SUITABLE_TASKS)).digest("hex");
}

export function agentTaskDeliverable() {
  return {
    title: "40 currently-open agent-suitable tasks from public freelance and bounty boards",
    checkedAt: AGENT_TASKS_CHECKED_AT,
    methodology: "Public listing pages only. No accounts were created, no applications were submitted, no posters were contacted, and no personal contact details were collected. If a public listing did not state a deadline, that field is explicitly marked as not stated rather than inferred.",
    rowCount: AGENT_SUITABLE_TASKS.length,
    proofSha256: agentTaskRowsSha256(),
    rows: AGENT_SUITABLE_TASKS,
  };
}
